services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8877:80"
    depends_on:
      - app
    container_name: laravel_project_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    # command: bash -c "php artisan migrate && php artisan config:cache && php artisan config:clear && php artisan db:seed && php-fpm"
    depends_on:
      - db
    container_name: laravel_project_app

  db:
    image: mysql:8.2
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravelprojecttask
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 8606:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: laravel_project_task_db
